apiVersion: apps/v1
kind: Deployment
metadata:
  name: food
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food
  template:
    metadata:
      labels:
        app: food
    spec:
      containers:
      - name: food
        image: ravi2krishna/food
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: food
  namespace: qa
spec:
  type: NodePort
  selector:
    app: food
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008